/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "on-secondary-container": "#616363",
          "primary": "#000000",
          "on-surface-variant": "#4c4546",
          "surface": "#f9f9f9",
          "on-surface": "#1b1b1b",
          "on-error": "#ffffff",
          "on-primary-container": "#848484",
          "on-tertiary-fixed-variant": "#474747",
          "surface-dim": "#dadada",
          "secondary-fixed": "#e2e2e2",
          "surface-container-low": "#f3f3f3",
          "inverse-primary": "#c6c6c6",
          "primary-container": "#1b1b1b",
          "outline": "#7e7576",
          "on-secondary-fixed-variant": "#454747",
          "tertiary-fixed": "#e2e2e2",
          "tertiary-fixed-dim": "#c6c6c6",
          "background": "#f9f9f9",
          "surface-container-high": "#e8e8e8",
          "on-tertiary-fixed": "#1b1b1b",
          "tertiary": "#000000",
          "on-primary-fixed": "#1b1b1b",
          "surface-container-highest": "#e2e2e2",
          "secondary-fixed-dim": "#c6c6c7",
          "on-primary-fixed-variant": "#474747",
          "surface-tint": "#5e5e5e",
          "error-container": "#ffdad6",
          "primary-fixed": "#e2e2e2",
          "surface-container-lowest": "#ffffff",
          "on-tertiary": "#ffffff",
          "error": "#ba1a1a",
          "secondary": "#5d5f5f",
          "tertiary-container": "#1b1b1b",
          "on-secondary-fixed": "#1a1c1c",
          "surface-bright": "#f9f9f9",
          "on-background": "#1b1b1b",
          "on-error-container": "#93000a",
          "on-primary": "#ffffff",
          "secondary-container": "#dfe0e0",
          "surface-container": "#eeeeee",
          "inverse-surface": "#303030",
          "on-tertiary-container": "#848484",
          "on-secondary": "#ffffff",
          "inverse-on-surface": "#f1f1f1",
          "primary-fixed-dim": "#c6c6c6",
          "outline-variant": "#cfc4c5",
          "surface-variant": "#e2e2e2"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "gutter": "24px",
          "stack-lg": "32px",
          "margin-mobile": "16px",
          "margin-desktop": "48px",
          "unit": "8px",
          "stack-xl": "64px",
          "stack-sm": "8px",
          "container-max": "1200px",
          "stack-md": "16px"
      },
      "fontFamily": {
          "display": ["Inter", "sans-serif"],
          "body-lg": ["Inter", "sans-serif"],
          "label-sm": ["Inter", "sans-serif"],
          "headline-md": ["Inter", "sans-serif"],
          "body-md": ["Inter", "sans-serif"],
          "headline-lg-mobile": ["Inter", "sans-serif"],
          "headline-lg": ["Inter", "sans-serif"],
          "label-md": ["Inter", "sans-serif"]
      },
      "fontSize": {
          "display": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800" }],
          "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
          "label-sm": ["12px", { "lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "500" }],
          "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
          "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
          "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "700" }],
          "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700" }],
          "label-md": ["14px", { "lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
